version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
      - UPSTREAM_REPO=${UPSTREAM_REPO}
      - UPSTREAM_BRANCH=${UPSTREAM_BRANCH}
      - BOT_TOKEN=${BOT_TOKEN}
